spring:
  application:
    name: station-project-frontend

  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email

logging:
  level:
    org:
      thymeleaf: DEBUG
      springframework:
        security: DEBUG

server:
  port: 8086

# Custom RMA-related configuration
address:
  base:
    url: http://uatbfssecure.rma.org.bt:8080/BFSSecure/nvpapi

beneficiary:
  benf_id: BE10000221

keys:
  private-path: classpath:pki/BE10000221.key
